Sokuuhotu/Sokuuhotu/Controllers/BidController.cs
using BAW.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace BAW.Controllers
{
    public class BidController : Controller
    {




        private readonly BidService _service;



        public BidController(BidService service)
        {
            _service = service;
        }


        public BidController() : this(new BidService())
        {

        }



        public async Task<ActionResult> BidReceived(int proId, int price)
        {

            var userId = User.Identity.GetUserId();

            var mesg = await _service.AcceptBidAsync(proId, userId, price);

            if (mesg != "")
            {
                TempData["Message"] = "only 2 bid";

                return RedirectToAction("ProductDetails", "Store", new { Id = proId });




            }


            return RedirectToAction("BidsHistory");


        }



        public async Task<ActionResult> BidsHistory()
        {


            var userId = User.Identity.GetUserId();

            var history = await _service.BidsHistoryAsync(userId);

            return View(history);

        }



        public async Task<ActionResult> PostedProduct()
        {


            var userId = User.Identity.GetUserId();

            var products = await _service.GetPostedProductsAsync(userId);

            return View(products);

        }



        public async Task<ActionResult> AllBidsByProduct(int proId)
        {


            //var userId = User.Identity.GetUserId();

            var bidrequest = await _service.GetProductBidsByIdAsync(proId);

            return View(bidrequest);

        }




    }
}

Sokuuhotu/Sokuuhotu/Views/Bid/AllBidsByProduct.cshtml
@model BAW.ViewModels.BidsByProduct

@{
    ViewBag.Title = "AllBidsByProduct";
    Layout = "~/Views/Shared/_BuyerSellerLayout.cshtml";
}





<!--************************************
             Dashboard Banner Start
     *************************************-->
<div class="tg-dashboardbanner">
    <h1>All Bids on your Product</h1>

    <div style="display:inline-block;background-color:rgba(229, 102, 37, 0.77);line-height:80px;margin:5px 0 0 55px;">

        <span style="color:white">Max Bid so far:</span> <b>@Model.MaxBid</b>



    </div>

</div>
<!--************************************
        Dashboard Banner End
*************************************-->
<!--************************************
                Main Start
        *************************************-->
<main id="tg-main" class="tg-main tg-haslayout">
    <!--************************************
            Section Start
    *************************************-->
    <section class="tg-dbsectionspace tg-haslayout">
        <div class="row">

            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="tg-dashboardbox">
                    <div class="tg-dashboardboxtitle">
                        <h2>Bidders</h2>

                        <button id="first">First Time Bid</button>
                        <button id="second">Second Time Bid</button>

                    </div>
                    <div class="tg-dashboardholder">

                        <table id="tg-adstype" class="table tg-dashboardtable tg-tablemyads">
                            <thead>
                                <tr>

                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Contact</th>
                                    <th>Price</th>
                                    <th>Bid Date</th>





                                </tr>
                            </thead>
                            <tbody id="firstbid">





                                @foreach (var item in Model.FirstBidsOfProduct)
                                {

                                    <tr data-category="active">

                                        <td data-title="Photo">@item.User.Email</td>
                                        <td data-title="Title">
                                            <h3>@item.User.Email</h3>

                                        </td>
                                        <td data-title="Category"><span class="tg-adcategories">03249429698</span></td>
                                        <td data-title="Featured">@item.Price</td>
                                        <td data-title="Ad Status"><span class="tg-adstatus tg-adstatusactive">@item.BidDate.ToShortDateString()</span></td>







                                    </tr>
                                }




                            </tbody>

                            <tbody id="secondbid">



                                @foreach (var item in Model.SecondBidsOfProduct)
                                {

                                    <tr data-category="active">

                                        <td data-title="Photo">@item.User.Email</td>
                                        <td data-title="Title">
                                            <h3>@item.User.Email</h3>

                                        </td>
                                        <td data-title="Category"><span class="tg-adcategories">03249429698</span></td>
                                        <td data-title="Featured">@item.Price</td>
                                        <td data-title="Ad Status"><span class="tg-adstatus tg-adstatusactive">@item.BidDate.ToShortDateString()</span></td>







                                    </tr>
                                }








                            </tbody>







                        </table>
                        <nav class="tg-pagination">
                            <ul>
                                <li class="tg-prevpage"><a href="#"><i class="fa fa-angle-left"></i></a></li>
                                <li><a href="#">1</a></li>
                                <li><a href="#">2</a></li>
                                <li><a href="#">3</a></li>
                                <li><a href="#">4</a></li>
                                <li class="tg-active"><a href="#">5</a></li>
                                <li>...</li>
                                <li><a href="#">10</a></li>
                                <li class="tg-nextpage"><a href="#"><i class="fa fa-angle-right"></i></a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>

        </div>
    </section>
    <!--************************************
            Section End
    *************************************-->
</main>
<!--************************************
        Main End
*************************************-->

Sokuuhotu/Sokuuhotu/Views/Bid/BidsHistory.cshtml
@model BAW.ViewModels.BidsHistoryVM
@{
    ViewBag.Title = "BidsHistory";
    Layout = "~/Views/Shared/_BuyerSellerLayout.cshtml";
}




<!--************************************
             Dashboard Banner Start
     *************************************-->
<div class="tg-dashboardbanner">
    <h1>My Bid History</h1>
    
</div>
<!--************************************
        Dashboard Banner End
*************************************-->





<!--************************************
                Main Start
        *************************************-->
<main id="tg-main" class="tg-main tg-haslayout">
    <!--************************************
            Section Start
    *************************************-->
    <section class="tg-dbsectionspace tg-haslayout">
        <div class="row">
           
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="tg-dashboardbox">
                            <div class="tg-dashboardboxtitle">
                                <h2>Products</h2>
                               
                                <button  id="first">First Time Bid</button>
                                <button  id="second">Second Time Bid</button>
                            
                            </div>
                            <div class="tg-dashboardholder">
                        
                                <table id="tg-adstype" class="table tg-dashboardtable tg-tablemyads">
                                    <thead>
                                        <tr>

                                            <th>Photo</th>
                                            <th>Title</th>
                                            <th>Category</th>
                                            <th>Price</th>
                                            
                                            <th>Bid Date</th>
                                          

                                          
                                          
                                           
                                        </tr>
                                    </thead>
                                    <tbody id="firstbid">


                                       
                                      @foreach (var item in Model.FirstTimeBid)
                                      {

                                        <tr data-category="active">

                                            <td data-title="Photo"><img src="~/Images/img-02.jpg" alt="image description" style="height:80px;width:120px;margin-left:30px"></td>
                                            <td data-title="Title">
                                                <h3>@item.Product.ProductName</h3>
                                                
                                            </td>
                                            <td data-title="Category"><span class="tg-adcategories">@item.Product.Category.CategoryName</span></td>
                                            <td data-title="Featured">@item.Price</td>
                                            <td data-title="Ad Status"><span class="tg-adstatus tg-adstatusactive">Jun 27</span></td>
                                            
                                           

                                      
                                            
                                          
                                        </tr>
                                      }
                                        

                                 



                                      

                                    </tbody>

                                    <tbody id="secondbid">



                                        @foreach (var item in Model.SecondTimeBid)
                                        {

                                            <tr data-category="active">

                                                <td data-title="Photo"><img src="~/Images/img-02.jpg" alt="image description" style="height:80px;width:120px;margin-left:30px"></td>
                                                <td data-title="Title">
                                                    <h3>@item.Product.ProductName</h3>

                                                </td>
                                                <td data-title="Category"><span class="tg-adcategories">@item.Product.Category.CategoryName</span></td>
                                                <td data-title="Featured">@item.Price</td>
                                                <td data-title="Ad Status"><span class="tg-adstatus tg-adstatusactive">Jun 27</span></td>






                                            </tr>
                                        }



                                    </tbody>


                                </table>
                                <nav class="tg-pagination">
                                    <ul>
                                        <li class="tg-prevpage"><a href="#"><i class="fa fa-angle-left"></i></a></li>
                                        <li><a href="#">1</a></li>
                                        <li><a href="#">2</a></li>
                                        <li><a href="#">3</a></li>
                                        <li><a href="#">4</a></li>
                                        <li class="tg-active"><a href="#">5</a></li>
                                        <li>...</li>
                                        <li><a href="#">10</a></li>
                                        <li class="tg-nextpage"><a href="#"><i class="fa fa-angle-right"></i></a></li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                
        </div>
    </section>
    <!--************************************
            Section End
    *************************************-->
</main>
<!--************************************
        Main End
*************************************-->

Sokuuhotu/Sokuuhotu/Views/Bid/PostedProduct.cshtml
@model IEnumerable<BAW.Models.Product>
@{
    ViewBag.Title = "PostedProduct";
    Layout = "~/Views/Shared/_BuyerSellerLayout.cshtml";
}














<!--************************************
             Dashboard Banner Start
     *************************************-->
<div class="tg-dashboardbanner">
    <h1>Items For Bid</h1>

</div>
<!--************************************
        Dashboard Banner End
*************************************-->
<!--************************************
                Main Start
        *************************************-->
<main id="tg-main" class="tg-main tg-haslayout">
    <!--************************************
            Section Start
    *************************************-->
    <section class="tg-dbsectionspace tg-haslayout">
        <div class="row">

            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="tg-dashboardbox">
                    <div class="tg-dashboardboxtitle">
                        <h2>Products</h2>

                    </div>
                    <div class="tg-dashboardholder">

                        <table id="tg-adstype" class="table tg-dashboardtable tg-tablemyads">
                            <thead>
                                <tr>

                                    <th>Photo</th>
                                    <th>Title</th>
                                    <th>Category</th>
                                    <th>Price</th>
                                   

                                    <th>Post Date</th>
                                    <th>End Date</th>


                                    <th>Action <small>View Bids | Delete</small> </th>



                                </tr>
                            </thead>
                            <tbody>



                                @foreach (var item in Model)
                                {

                                    <tr data-category="active">

                                        <td data-title="Photo"><img src="~/Images/img-02.jpg" alt="image description" style="height:80px;width:120px;margin-left:30px"></td>
                                        <td data-title="Title">
                                            <h3 style="color:#040063; text-align:center" >@item.ProductName</h3>

                                        </td>
                                        <td data-title="Category"><span class="tg-adcategories">@item.Category.CategoryName</span></td>
                                        <td data-title="Featured">$</td>
                                        <td data-title="Ad Status"><span class="tg-adstatus tg-adstatusactive">@item.StartDate.ToShortDateString()</span></td>
                                        <td data-title="Ad Status"><span class="tg-adstatus tg-adstatusactive">@item.EndDate.ToShortDateString()</span></td>



                                        <td data-title="Action">
                                            <div class="tg-btnsactions">
                                                <a class="tg-btnaction tg-btnactionview" href="@Url.Action("AllBidsByProduct","Bid", new { proId = item.ProductId })"><i class="fa fa-eye"></i><small></small> </a>
                                                <a class="tg-btnaction tg-btnactiondelete" href="javascript:void(0);"><i class="fa fa-trash"></i></a>
                                            </div>
                                        </td>



                                    </tr>
                                }








                            </tbody>

                        


                        </table>
                        <nav class="tg-pagination">
                            <ul>
                                <li class="tg-prevpage"><a href="#"><i class="fa fa-angle-left"></i></a></li>
                                <li><a href="#">1</a></li>
                                <li><a href="#">2</a></li>
                                <li><a href="#">3</a></li>
                                <li><a href="#">4</a></li>
                                <li class="tg-active"><a href="#">5</a></li>
                                <li>...</li>
                                <li><a href="#">10</a></li>
                                <li class="tg-nextpage"><a href="#"><i class="fa fa-angle-right"></i></a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>

        </div>
    </section>
    <!--************************************
            Section End
    *************************************-->
</main>
<!--************************************
        Main End
*************************************-->